param(
  [Parameter(Mandatory = $true)]
  [string]$Version,

  [string]$InstallerUrl,

  [string]$InstallerPath,

  [string]$OutputRoot = "winget-manifests",

  [ValidatePattern('^\d{4}-\d{2}-\d{2}$')]
  [string]$ReleaseDate = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd")
)

$ErrorActionPreference = "Stop"

$PackageIdentifier = "OwenMcGirr.UsefulTopmost"
$Publisher = "Owen McGirr"
$PackageName = "Useful Topmost"
$PackageUrl = "https://github.com/OwenMcGirr/useful-topmost"
$LicenseUrl = "https://github.com/OwenMcGirr/useful-topmost/blob/main/LICENSE"
$ShortDescription = "Frameless full-screen Electron dashboard whose widgets are generated by the OpenAI Codex CLI."
$ManifestVersion = "1.12.0"

if ([string]::IsNullOrWhiteSpace($InstallerUrl)) {
  $InstallerUrl = "https://github.com/OwenMcGirr/useful-topmost/releases/download/v$Version/useful-topmost-$Version-win-x64.exe"
}

function ConvertTo-YamlString([string]$Value) {
  return '"' + $Value.Replace('\', '\\').Replace('"', '\"') + '"'
}

function Get-InstallerHash {
  param(
    [string]$Url,
    [string]$Path
  )

  if (-not [string]::IsNullOrWhiteSpace($Path)) {
    if (-not (Test-Path -LiteralPath $Path)) {
      throw "InstallerPath does not exist: $Path"
    }
    return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToUpperInvariant()
  }

  $tempPath = Join-Path ([System.IO.Path]::GetTempPath()) ([System.IO.Path]::GetRandomFileName() + ".exe")
  try {
    Invoke-WebRequest -Uri $Url -OutFile $tempPath
    return (Get-FileHash -LiteralPath $tempPath -Algorithm SHA256).Hash.ToUpperInvariant()
  } finally {
    Remove-Item -LiteralPath $tempPath -ErrorAction SilentlyContinue
  }
}

$installerSha256 = Get-InstallerHash -Url $InstallerUrl -Path $InstallerPath

$manifestDir = Join-Path $OutputRoot "manifests\o\OwenMcGirr\UsefulTopmost\$Version"
New-Item -ItemType Directory -Path $manifestDir -Force | Out-Null

$versionManifest = @"
# yaml-language-server: `$schema=https://aka.ms/winget-manifest.version.$ManifestVersion.schema.json
# Created with scripts/winget-manifest.ps1
PackageIdentifier: $PackageIdentifier
PackageVersion: $Version
DefaultLocale: en-US
ManifestType: version
ManifestVersion: $ManifestVersion
"@

$localeManifest = @"
# yaml-language-server: `$schema=https://aka.ms/winget-manifest.defaultLocale.$ManifestVersion.schema.json
# Created with scripts/winget-manifest.ps1
PackageIdentifier: $PackageIdentifier
PackageVersion: $Version
PackageLocale: en-US
Publisher: $(ConvertTo-YamlString $Publisher)
PublisherUrl: $PackageUrl
Author: $(ConvertTo-YamlString $Publisher)
PackageName: $(ConvertTo-YamlString $PackageName)
PackageUrl: $PackageUrl
License: MIT
LicenseUrl: $LicenseUrl
Copyright: Copyright (c) 2026 Owen McGirr
ShortDescription: $(ConvertTo-YamlString $ShortDescription)
Moniker: useful-topmost
Tags:
- electron
- codex
- dashboard
- widgets
- utility
ManifestType: defaultLocale
ManifestVersion: $ManifestVersion
"@

$installerManifest = @"
# yaml-language-server: `$schema=https://aka.ms/winget-manifest.installer.$ManifestVersion.schema.json
# Created with scripts/winget-manifest.ps1
PackageIdentifier: $PackageIdentifier
PackageVersion: $Version
InstallerType: nullsoft
Scope: user
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: $ReleaseDate
Installers:
- Architecture: x64
  InstallerUrl: $InstallerUrl
  InstallerSha256: $installerSha256
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: OpenAI.Codex
ManifestType: installer
ManifestVersion: $ManifestVersion
"@

Set-Content -LiteralPath (Join-Path $manifestDir "$PackageIdentifier.yaml") -Value $versionManifest -Encoding utf8
Set-Content -LiteralPath (Join-Path $manifestDir "$PackageIdentifier.locale.en-US.yaml") -Value $localeManifest -Encoding utf8
Set-Content -LiteralPath (Join-Path $manifestDir "$PackageIdentifier.installer.yaml") -Value $installerManifest -Encoding utf8

Write-Host "Wrote WinGet manifests to $manifestDir"
Write-Host "InstallerSha256: $installerSha256"
Write-Host "Validate with: winget validate $manifestDir"
